-- ============================================
-- Script d'insertion des PAT (Personnel Administratif et Technique)
-- À exécuter après avoir inséré les assistants
-- ============================================

-- Insérer les PAT du CSV avec quota_surveillances = 0 par défaut
-- Note: Si EFT T. est vide, on utilise EFT R. comme etp_total
INSERT INTO surveillants (nom, prenom, email, type, affectation_faculte, etp_total, etp_recherche, etp_autre, categorie_presence, fin_absence, fin_repos_postnatal, quota_surveillances, is_active) VALUES
('Affan', 'Hala', 'hala.affan@uclouvain.be', 'pat', 'FSP', 0.8, 0.8, NULL, NULL, NULL, '2025-12-03', 0, true),
('Agbekponou', 'Afi', 'sandrine.agbekponou@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Andriamanampisoa', 'Maëlle', 'maelle.andriamanampisoa@uclouvain.be', 'pat', 'FASB', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Araujo Vargas', 'Guillermo Alain', 'guillermo.araujo@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Arnould', 'Guillaume', 'guillaume.arnould@uclouvain.be', 'pat', 'FASB', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Bali', 'Camilia', 'camilia.bali@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Beersaerts', 'Melanie', 'melanie.beersaerts@uclouvain.be', 'pat', 'MEDE', 0.7, NULL, NULL, NULL, NULL, '2025-12-31', 0, true),
('Benoit', 'Théo', 'theo.benoit@uclouvain.be', 'pat', 'ASS', 0.4, NULL, NULL, NULL, NULL, NULL, 0, true),
('Bourlet', 'Maude', 'maude.bourlet@uclouvain.be', 'pat', 'FASB', 1, NULL, 0.2, 'Crédit temps classique', '2028-12-31', NULL, 0, true),
('Brabant', 'Sara', 'sara.brabant@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, '2025-12-31', 0, true),
('Charles-Pirlot', 'Nicolas', 'nicolas.charles@uclouvain.be', 'pat', 'MEDE', 1, NULL, 0.5, 'Mi-temps médical', '2025-10-31', NULL, 0, true),
('Colak', 'Ramazan', 'ramazan.colak@uclouvain.be', 'pat', 'FASB', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Cordier', 'Stéphane', 'stephane.cordier@uclouvain.be', 'pat', 'FSM', 0.8, NULL, NULL, NULL, NULL, '2025-12-31', 0, true),
('Culot', 'Nathalie', 'nathalie.culot@uclouvain.be', 'pat', 'FASB', 0.65, NULL, NULL, NULL, NULL, NULL, 0, true),
('Cumps', 'Julien', 'julien.cumps@uclouvain.be', 'pat', 'ASS', 0.8, NULL, NULL, NULL, NULL, '2026-01-26', 0, true),
('De Boeck', 'Nicolas', 'nicolas.deboeck@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('De Loof', 'Marine', 'm.deloof@uclouvain.be', 'pat', 'MEDE', 0.8, NULL, NULL, NULL, NULL, '2026-09-14', 0, true),
('De Meyer', 'Camille', 'camille.demeyer@uclouvain.be', 'pat', 'MEDE', 0.8, NULL, NULL, NULL, NULL, NULL, 0, true),
('De Waele', 'Anne', 'anne.dewaele@uclouvain.be', 'pat', 'MEDE', 0.9, NULL, 0.2, 'Crédit-temps fin carrière', '2028-02-29', NULL, 0, true),
('Dehaine', 'Danielle', 'danielle.dehaine@uclouvain.be', 'pat', 'MEDE', 0.58, NULL, NULL, NULL, NULL, NULL, 0, true),
('Delhaye', 'Delphine', 'delphine.delhaye@uclouvain.be', 'pat', 'FASB', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Delvaux', 'Delphine', 'delphine.delvaux@uclouvain.be', 'pat', 'ASS', 0.5, NULL, NULL, NULL, NULL, '2026-08-23', 0, true),
('Demaret', 'Maxime', 'maxime.demaret@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Draime', 'Amandine', 'amandine.draime@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Drappier', 'Marjorie', 'marjorie.drappier@uclouvain.be', 'pat', 'FSM', 0.9, NULL, NULL, NULL, NULL, NULL, 0, true),
('Driessen', 'Julie', 'julie.driessen@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('El Kaddouri', 'Ali', 'ali.elkaddouri@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Flamand', 'Claire', 'claire.flamand@uclouvain.be', 'pat', 'FSP', 0.7, NULL, NULL, NULL, NULL, NULL, 0, true),
('Gillot', 'Céline', 'celine.gillot@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Gisellu', 'Giovanna', 'giovanna.gisellu@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Gits', 'Aline', 'aline.gits@uclouvain.be', 'pat', 'ASS', 0.8, NULL, NULL, NULL, NULL, NULL, 0, true),
('Goudmaeker', 'Apolline', 'apolline.goudmaeker@uclouvain.be', 'pat', 'ASS', 0.8, NULL, NULL, NULL, NULL, NULL, 0, true),
('Haddad Ouriaghli', 'Mariem', 'mariem.haddad@uclouvain.be', 'pat', 'FASB', 0.75, NULL, NULL, NULL, NULL, NULL, 0, true),
('Herent', 'Marie-France', 'marie-france.herent@uclouvain.be', 'pat', 'FASB', 0.8, NULL, NULL, NULL, NULL, NULL, 0, true),
('Hudders', 'Walter', 'walter.hudders@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Ingabire', 'Sabrina', 'sabrina.ingabire@uclouvain.be', 'pat', 'ASS', 0.5, NULL, NULL, NULL, NULL, NULL, 0, true),
('Janssens', 'Ambre', 'ambre.janssens@uclouvain.be', 'pat', 'FSM', 0.5, NULL, NULL, NULL, NULL, '2027-09-21', 0, true),
('Jaucot', 'Simon', 'simon.jaucot@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Jeanty', 'Philippe', 'philippe.jeanty@uclouvain.be', 'pat', 'ASS', 1, NULL, 0.5, 'Mi-temps médical', '2025-12-31', NULL, 0, true),
('Ketelaer', 'Nicolas', 'nicolas.ketelaer@uclouvain.be', 'pat', 'FSM', 0.5, NULL, NULL, NULL, NULL, NULL, 0, true),
('Krajnc', 'Pierre', 'pierre.krajnc@uclouvain.be', 'pat', 'FSP', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Lannoye', 'David', 'david.lannoye@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Lawson', 'Latevi Armand', 'latevi.lawson@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Lecouturier', 'Nathalie', 'nathalie.lecouturier@uclouvain.be', 'pat', 'FASB', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Lukeba Baziota', 'Anne-Marie', 'anne-marie.lukeba@uclouvain.be', 'pat', 'FASB', 0.4, NULL, NULL, NULL, NULL, NULL, 0, true),
('Marquet', 'Nicolas', 'nicolas.marquet@uclouvain.be', 'pat', 'FASB', 1, NULL, 0.2, 'Crédit temps classique', '2029-07-31', NULL, 0, true),
('Massaoudi', 'Taieb', 'taieb.massaoudi@uclouvain.be', 'pat', 'ASS', 1, NULL, 1, 'Maladie > 1 an (E+O)', '2025-12-31', NULL, 0, true),
('Mazzagufo', 'Jenny', 'jenny.mazzagufo@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Mestrez', 'Virginie', 'virginie.mestrez@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('M''Hamed', 'Sabine', 'sabine.mhamed@uclouvain.be', 'pat', 'FSM', 0.8, NULL, NULL, NULL, NULL, NULL, 0, true),
('Mura', 'Mirella', 'mirella.mura@uclouvain.be', 'pat', 'FSM', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Nassel', 'Ludovic', 'ludovic.nassel@uclouvain.be', 'pat', 'FSM', 0.7, NULL, NULL, NULL, NULL, '2026-05-19', 0, true),
('Ntamashimikiro', 'Sandrine', 'sandrine.ntamashimikiro@uclouvain.be', 'pat', 'ASS', 1, NULL, 0.2, 'Crédit temps classique', '2026-04-30', NULL, 0, true),
('Ouled Haddou', 'Nadia', 'nadia.ouledhaddou@uclouvain.be', 'pat', 'ASS', 0.5, NULL, NULL, NULL, NULL, NULL, 0, true),
('Pablos Martin', 'Carmen', 'carmen.pablos@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Palmai-Pallag', 'Mihaly', 'mihaly.palmai@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Peng', 'Liang-Yen', 'liang-yen.peng@uclouvain.be', 'pat', 'ASS', 1, NULL, NULL, NULL, NULL, '2026-09-15', 0, true),
('Relvas', 'Carine', 'carine.relvas@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Rouard', 'Philippe', 'philippe.rouard@uclouvain.be', 'pat', 'ASS', 1, NULL, 1, 'Détachement remboursé', '9999-12-31', NULL, 0, true),
('Ruiz Vicente', 'Carlos', 'carlos.ruizvicente@uclouvain.be', 'pat', 'MEDE', 0.8, NULL, NULL, NULL, NULL, '2026-02-04', 0, true),
('Salehi', 'Majid', 'majid.salehi@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Schockaert', 'Sarah', 'sarah.schockaert@uclouvain.be', 'pat', 'MEDE', 0.75, NULL, NULL, NULL, NULL, NULL, 0, true),
('Serruys', 'Kathleen', 'kathleen.serruys@uclouvain.be', 'pat', 'ASS', 0.5, NULL, NULL, NULL, NULL, NULL, 0, true),
('Tahri', 'Yousra', 'yousra.tahri@uclouvain.be', 'pat', 'ASS', 0.4, NULL, NULL, NULL, NULL, NULL, 0, true),
('Titeux', 'Fabienne', 'fabienne.titeux@uclouvain.be', 'pat', 'ASS', 0.9, NULL, NULL, NULL, NULL, NULL, 0, true),
('van Eetvelde', 'Géraldine', 'geraldine.vaneetvelde@uclouvain.be', 'pat', 'MEDE', 1, NULL, 0.2, 'Mi-temps médical', '2025-12-31', '2025-12-31', 0, true),
('Vanbellaiengh', 'Séverine', 'severine.vanbellaiengh@uclouvain.be', 'pat', 'FASB', 0.7, NULL, NULL, NULL, NULL, NULL, 0, true),
('Vandercappellen', 'Romane', 'romane.vandercappellen@uclouvain.be', 'pat', 'MEDE', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Vanvarenberg', 'Kevin', 'kevin.vanvarenberg@uclouvain.be', 'pat', 'FASB', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Vergauwen', 'Martial', 'martial.vergauwen@uclouvain.be', 'pat', 'FASB', 1, NULL, 0.2, 'Crédit temps classique', '2026-04-26', NULL, 0, true),
('Vermeylen', 'Séverine', 'severine.vermeylen@uclouvain.be', 'pat', 'FASB', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Walravens', 'Christine', 'christine.walravens@uclouvain.be', 'pat', 'FSM', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Wangneur', 'Claudine', 'claudine.wangneur@uclouvain.be', 'pat', 'FSP', 1, NULL, NULL, NULL, NULL, NULL, 0, true),
('Zabeau', 'Héline', 'heline.zabeau@uclouvain.be', 'pat', 'FSP', 0.35, NULL, NULL, NULL, NULL, '2026-01-12', 0, true)
ON CONFLICT (email) DO NOTHING;

-- Afficher un résumé
SELECT 
    type,
    COUNT(*) as nombre,
    SUM(CASE WHEN quota_surveillances > 0 THEN 1 ELSE 0 END) as avec_quota
FROM surveillants
GROUP BY type
ORDER BY type;
