-- ============================================
-- Script d'insertion des surveillants depuis le CSV
-- À exécuter APRÈS avoir mis à jour la structure de la table
-- ============================================

-- Supprimer les données de test
DELETE FROM surveillants WHERE email LIKE 'test%@example.com';

-- Insérer les surveillants du CSV
INSERT INTO surveillants (nom, prenom, email, type, affectation_faculte, affectation_institut, statut_salarial, etp_total, etp_recherche, etp_autre, categorie_presence, fin_absence, fin_repos_postnatal, type_occupation, quota_surveillances, is_active) VALUES
('Akue', 'Mathilde', 'mathilde.akue@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Albert', 'Lisa', 'lisa.albert@uclouvain.be', 'assistant', 'FSP', 'IRSS', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Alves Jorge', 'Sara', 'sara.alvesjorge@uclouvain.be', 'assistant', 'FSP', 'IPSY', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('André', 'Grégoire', 'gregoire.andre@uclouvain.be', 'assistant', 'ASS', 'IREC', 'ST', 0.8, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 5, true),
('Assoignon', 'Théo', 'theo.assoignon@uclouvain.be', 'assistant', 'ASS', 'IREC', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Atik', 'Hicham', 'hicham.atik@uclouvain.be', 'assistant', 'MEDE', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Auquière', 'Marie', 'marie.auquiere@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Barbé', 'Alice', 'alice.barbe@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Bauduin', 'Ségolène', 'segolene.bauduin@uclouvain.be', 'assistant', 'FSM', 'IACS', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Benaissa', 'Doua', 'doua.benaissa@uclouvain.be', 'assistant', 'FASB', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Berridi Chamorro', 'Laia', 'laia.berridi@uclouvain.be', 'assistant', 'FASB', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Bigorne', 'Alexia', 'alexia.bigorne@uclouvain.be', 'assistant', 'FSP', 'IRSS', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Bonneels', 'Philippe', 'philippe.bonneels@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 0.2, NULL, NULL, NULL, '2026-09-14', NULL, 'ST intéri', 1, true),
('Boulle', 'Roxane', 'roxane.boulle@uclouvain.be', 'assistant', 'FASB', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Braconnier', 'Pauline', 'pauline.braconnier@uclouvain.be', 'assistant', 'FASB', 'IONS', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Calà', 'Ornella', 'ornella.cala@uclouvain.be', 'assistant', 'ASS', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Charlier', 'Mathilde', 'mathilde.charlier@uclouvain.be', 'assistant', 'MEDE', 'IONS', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Cornelis', 'Gilles', 'gilles.cornelis@uclouvain.be', 'assistant', 'MEDE', 'IRSS', 'ST', 0.5, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 3, true),
('Courtain', 'Christel', 'christel.courtain@uclouvain.be', 'assistant', 'FASB', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Da Purificaçao', 'Julien', 'julien.da@uclouvain.be', 'assistant', 'MEDE', 'IREC', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('de Montigny', 'Manon', 'manon.demontigny@uclouvain.be', 'assistant', 'MEDE', 'IRSS', 'ST', 0.5, NULL, NULL, NULL, '2026-09-30', NULL, NULL, 3, true),
('De Rijck Muhl', 'Laura', 'laura.derijckmuhl@uclouvain.be', 'assistant', 'FSM', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Dechenne', 'Juhans', 'juhans.dechenne@uclouvain.be', 'assistant', 'ASS', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Declerck', 'Salomé', 'salome.declerck@uclouvain.be', 'assistant', 'FASB', 'IREC', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Deghorain', 'Fanny', 'fanny.deghorain@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 1, NULL, NULL, NULL, '2027-10-12', NULL, NULL, 6, true),
('Degraux', 'Margot', 'margot.degraux@uclouvain.be', 'assistant', 'ASS', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Dembour', 'Pascaline', 'pascaline.dembour@uclouvain.be', 'assistant', 'FSP', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Denis', 'Corentin', 'corentin.denis@uclouvain.be', 'assistant', 'FSM', 'IREC', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Devis', 'Julie', 'julie.devis@uclouvain.be', 'assistant', 'FASB', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Djurkin', 'Andrej', 'andrej.djurkin@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 0.2, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 1, true),
('El Bakkali', 'Imane', 'imane.elbakkali@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Fayt', 'Clémence', 'clemence.fayt@uclouvain.be', 'assistant', 'ASS', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Francotte', 'Benjamin', 'benjamin.francotte@uclouvain.be', 'assistant', 'FSM', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Frederic', 'Doriane', 'doriane.frederic@uclouvain.be', 'assistant', 'FASB', 'DDUV', 'ST', 1, NULL, 0.5, 'Mi-temps médical', '2025-12-31', '2027-09-14', NULL, 6, true),
('Fuchs', 'Victoria', 'victoria.fuchs@uclouvain.be', 'assistant', 'FSP', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Garin', 'Hélène', 'helene.garin@uclouvain.be', 'assistant', 'FSP', 'IRSS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Gely', 'Lucile', 'lucile.gely@uclouvain.be', 'assistant', 'FSM', 'IREC', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Ghodsi', 'Marine', 'marine.ghodsi@uclouvain.be', 'assistant', 'FASB', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Girard', 'Aurore', 'aurore.girard@uclouvain.be', 'assistant', 'MEDE', 'IRSS', 'ST', 0.5, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 3, true),
('Glaudot', 'Guillaume', 'guillaume.glaudot@uclouvain.be', 'assistant', 'MEDE', 'IONS', 'ST', 0.8, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 5, true),
('Guiheneuf', 'Camille', 'camille.guiheneuf@uclouvain.be', 'assistant', 'FSP', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Guyot', 'Léopold', 'leopold.guyot@uclouvain.be', 'assistant', 'FASB', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Hajj Hassan', 'Yara', 'yara.hajjhassan@uclouvain.be', 'assistant', 'FASB', 'IREC', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Hansoulle', 'Thomas', 'thomas.hansoulle@uclouvain.be', 'assistant', 'MEDE', 'IREC', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Hoflack', 'Laurie', 'laurie.hoflack@uclouvain.be', 'assistant', 'MEDE', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Hunin', 'Olivier', 'olivier.hunin@uclouvain.be', 'assistant', 'MEDE', 'IRSS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Iordanescu', 'Andra-Gabriela', 'andra-gabriela.iordanescu@uclouvain.be', 'assistant', 'ASS', 'IMCN', 'ST', 0.33, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 2, true),
('Irakoze', 'Armand', 'armand.irakoze@uclouvain.be', 'assistant', 'MEDE', 'IREC', 'ST', 0.4, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 2, true),
('Kathrada', 'Naajiyah', 'naajiyah.kathrada@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 0.8, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 5, true),
('Kisita', 'Victor', 'victor.kisita@uclouvain.be', 'assistant', 'FSM', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Lacour', 'Séraphin', 'seraphin.lacour@uclouvain.be', 'assistant', 'ASS', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Laghouati', 'Adam', 'adam.laghouati@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Lallement', 'Eurydice', 'eurydice.lallement@uclouvain.be', 'assistant', 'MEDE', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Leloup', 'Romane', 'romane.leloup@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Mahieu', 'David', 'david.mahieu@uclouvain.be', 'assistant', 'MEDE', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Marchand', 'Dorothée', 'dorothee.marchand@uclouvain.be', 'assistant', 'FASB', 'IREC', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Martou', 'Marie-Sophie', 'marie-sophie.martou@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Mathieu', 'Samuel', 'samuel.mathieu@uclouvain.be', 'assistant', 'FSM', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Mfumu Kandukulu', 'Valentia', 'valentia.mfumu@uclouvain.be', 'assistant', 'FSP', NULL, 'ST', 1, NULL, 1, 'Maternité', '2025-12-09', '2027-09-14', NULL, 6, true),
('Mievis', 'Gwenaëlle', 'gwenaelle.mievis@uclouvain.be', 'assistant', 'FASB', 'IONS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Mortier', 'Alexandre', 'a.mortier@uclouvain.be', 'assistant', 'FSM', 'IONS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Moulin', 'Marine', 'marine.moulin@uclouvain.be', 'assistant', 'FSM', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Niyigena', 'Emmanuel', 'emmanuel.niyigena@uclouvain.be', 'assistant', 'FASB', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Parrens', 'Paul', 'paul.parrens@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Petrossova', 'Eva', 'eva.petrossova@uclouvain.be', 'assistant', 'ASS', 'IRSS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Pierrard', 'Florence', 'florence.pierrard@uclouvain.be', 'assistant', 'FSP', NULL, 'ST', 0.3, 0.3, NULL, NULL, NULL, '2025-12-31', NULL, 2, true),
('Pierre Despas', 'Elisa', 'elisa.pierre@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 1, NULL, NULL, NULL, NULL, '2025-12-31', 'ST intéri', 6, true),
('Pionneau', 'Julie', 'julie.pionneau@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Quertinmont', 'Lisa', 'lisa.quertinmont@uclouvain.be', 'assistant', 'FSP', NULL, 'ST', 0.7, 0.7, NULL, NULL, NULL, '2025-12-31', NULL, 4, true),
('Quiquempoix', 'Sophie', 'sophie.quiquempoix@uclouvain.be', 'assistant', 'FASB', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Rasouli', 'Paria', 'paria.rasouli@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Sahloul', 'Sarah', 'sarah.sahloul@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 0.6, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 4, true),
('Savoyen', 'Perrine', 'perrine.savoyen@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Scacchitti', 'Cecilia', 'cecilia.scacchitti@uclouvain.be', 'assistant', 'FSP', 'IRSS', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Schmitz', 'Eliane', 'eliane.schmitz@uclouvain.be', 'assistant', 'MEDE', 'IRSS', 'ST', 0.3, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 2, true),
('Schroeder Chaidron', 'Léna', 'lena.schroeder@uclouvain.be', 'assistant', 'ASS', 'IREC', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Tedde', 'Mégane', 'megane.tedde@uclouvain.be', 'assistant', 'FSM', NULL, 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, 'ST intéri', 6, true),
('Temperman', 'Elsa', 'elsa.temperman@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Tonnelier', 'Margo', 'margo.tonnelier@uclouvain.be', 'assistant', 'FSP', 'IRSS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Toussaint', 'Thibaut', 'thibaut.toussaint@uclouvain.be', 'assistant', 'FSM', 'IONS', 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Trusgnach', 'Noah', 'noah.trusgnach@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Valentin', 'Stéphanie', 'stephanie.valentin@uclouvain.be', 'assistant', 'FASB', NULL, 'PX', 0.15, NULL, NULL, NULL, NULL, '2025-12-12', NULL, 1, true),
('van Doorslaer de ten Ryen', 'Sophie', 'sophie.vandoorslaer@uclouvain.be', 'assistant', 'FSM', 'IONS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Van Nedervelde', 'Louise', 'louise.vannedervelde@uclouvain.be', 'assistant', 'FASB', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-16', NULL, NULL, 6, true),
('Vancolen', 'Elisa', 'elisa.vancolen@uclouvain.be', 'assistant', 'FSM', 'IONS', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Vermersch', 'Victoria', 'victoria.vermersch@uclouvain.be', 'assistant', 'FASB', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Viera Olivera', 'Eloïse', 'eloise.viera@uclouvain.be', 'assistant', 'FASB', 'LDRI', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Vilela', 'Alexandre', 'alexandre.vilela@uclouvain.be', 'assistant', 'MEDE', NULL, 'ST', 1, NULL, NULL, NULL, '2027-09-14', NULL, NULL, 6, true),
('Wangermez', 'Camille', 'camille.wangermez@uclouvain.be', 'assistant', 'ASS', 'DDUV', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true),
('Wendo', 'Kevin', 'kevin.wendo@uclouvain.be', 'assistant', 'ASS', 'IREC', 'ST', 1, NULL, NULL, NULL, '2026-09-14', NULL, NULL, 6, true)
ON CONFLICT (email) DO NOTHING;
